Repository KiizanKiizan/Manene, pull requests merged in 2023-10, with the labels that each got.

#267 update: .env.local及びVPN設定方法の説明を追加
  README.md
Labels: documentation

#266 Feature/263/265 api関数hooksの作成
  app/_api/size_measurement/fetchSizeCalcIndex.tsx
  app/_api/size_measurement/fetchSizeStableShow.tsx
  app/_api/size_measurement/getSizeMeasurementIndex.tsx
  app/_api/size_measurement/useSizeMeasurementUpdate.tsx
Labels: アイテムサイズ計測

#281 Feature/263/274 sizemeasurementslistitem作成
  app/_components/size_measurements/[id]/size-measurements-list-item.tsx
  package.json
  yarn.lock
Labels: アイテムサイズ計測

#282 feat: SizeMeasurementsListの作成
  app/_components/size_measurements/[id]/size-measurements-list.tsx
Labels: アイテムサイズ計測

#283 fix: playwightのテストPR時に走らせないようにする
  .github/workflows/playwright.yml
Labels: good first issue
