Repository KiizanKiizan/Manene, pull requests merged in 2023-08, with the labels that each got.

#77 Feature 62 74 忘れ物apiフックス作成
  app/api/coorde_pick/lost_articles/useLostArticlesConfirm.ts
  app/api/coorde_pick/lost_articles/useLostArticlesCreate.ts
  app/api/usePostRequest.ts
Labels: 忘れ物管理

#82 Feature/61 78 lostarticlesdialogs作成
  .vscode/extensions.json
  app/api/coorde_pick/lost_articles/useLostArticlesConfirm.ts
  app/components/lost_articles/lost-articles-dialogs.tsx
Labels: 忘れ物管理

#83 feat: LostArticlesFormの作成
  app/components/lost_articles/lost_articles-form.tsx
Labels: 忘れ物管理

#84 feat: Html5QrcodeScannerライブラリを使用して、QRコードリーダー作成
  app/components/common/barcode/Html5QrcodePlugin.tsx
  app/components/common/barcode/qr-code-reader.tsx
  next.config.js
  package.json
  yarn.lock
Labels: コーデピック

#97 feat: LostArticlesContainerの作成
  app/components/lost_articles/lost-articles-confirm-fetcher.tsx
  app/components/lost_articles/lost-articles-container.tsx
  app/components/lost_articles/lost-articles-dialogs.tsx
  app/components/lost_articles/lost-articles-form.tsx
  app/lost_articles/page.tsx
Labels: 忘れ物管理

#95 feat: アイテムの詳細情報を取得する関数を作成
  app/api/item_detail/getItemsShow.ts
Labels: アイテム詳細表示

#112 Feature/90 96 アイテム詳細表示itemdetailcardの作成
  app/api/item_detail/getItemsShow.ts
  app/components/common/Image/expandable-image.tsx
  app/components/common/Item/item-detail-card-container.tsx
  app/components/common/Item/item-detail-card.tsx
  app/item_detail/[id]/page.tsx
Labels: アイテム詳細表示

#100 feat: 忘れ物登録テストの実装
  .github/workflows/playwright.yml
  .gitignore
  app/components/lost_articles/lost-articles-dialogs.tsx
  package.json
  playwright.config.ts
  tests-examples/demo-todo-app.spec.ts
  tests/lost_articles/lost_articles.spec.ts
  yarn.lock
Labels: 忘れ物管理

#109 feat: APIフックスの作成
  app/api/item-location/useItemLocationsItemScan.ts
  app/api/item-location/useItemLocationsMove.ts
  app/api/item-location/useItemsShow.ts
  app/api/usePatchRequest.ts
Labels: 棚移動

#114 Feature/61/107 itemlist作成
  app/api/item-location/useItemLocationsItemScan.ts
  app/components/common/Item/item-mini-card.tsx
  app/components/item_location/item-list.tsx
Labels: 棚移動

#120 Feature/68 104 アイテムピックのapi作成
  app/api/coorde_pick/useCoordePicksPick.ts
Labels: アイテムピック

#116 Feature/90 113 itemdetailpageの実装
  app/components/common/barcode/qr-code-reader.tsx
  app/components/item-detail/item-detail-container.tsx
  app/item_detail/page.tsx
Labels: アイテム詳細表示

#136 2. Feature/123/133 stocktakingrow作成
  app/api/stocktaking/getStocktakingsCurrent.ts
  app/components/stocktaking/stocktaking-row.tsx
  app/providers.tsx
Labels: 棚卸し

#137 3. feat: StocktakingListの作成
  app/components/stocktaking/stocktaking-list.tsx
Labels: 棚卸し

#150 4. feature/123/138-stocktakingcontainer作成'…
  app/api/stocktaking/useStocktakingsCreate.ts
  app/components/common/barcode/barcode-button.tsx
  app/components/common/dialog/loading-dialog.tsx
  app/components/common/pages/header.tsx
  app/components/stocktaking/stocktaking-container.tsx
  app/loading.tsx
  app/page.tsx
  app/service/toCamelCaseObject.ts
  app/stocktaking/page.tsx
Labels: 棚卸し

#144 5. Feature/123/140 itemlisttabswitcher作成
  app/components/stocktaking-location/location-item-tabs.tsx
  package.json
  yarn.lock
Labels: 棚卸し

#152 6. Feature/123/141 stocktakinglocationcontainerpageの作成2
  app/api/stocktaking-location/useStocktakingLocationItemScan.ts
  app/api/stocktaking-location/useStocktakingLocationMove.ts
  app/components/common/barcode/barcode-button.tsx
  app/components/common/button/scan-button.tsx
  app/components/common/dialog/disable-back-dialog.tsx
  app/components/common/pages/sub-header.tsx
  app/components/stocktaking-location/location-item-tabs.tsx
  app/components/stocktaking-location/stocktaking-location-container.tsx
  app/components/stocktaking/stocktaking-row.tsx
  app/constants/location.ts
  app/stocktaking/[id]/page.tsx
Labels: 棚卸し

#131 feat: testの作成
  app/components/common/Item/item-mini-card.tsx
  package.json
  tests/item_location/item_location.spec.ts
  yarn.lock
Labels: 棚移動

#149 feat: API関数作成
  app/api/item_status/getOptionsIndex.ts
  app/api/item_status/useItemsBulkUpdateStatus.ts
  app/api/item_status/useItemsValidateBulkUpdateStatus.ts
Labels: アイテムステータス

#154 Feature/146/148 itemstatuscontainer page作成
  app/api/item_status/getOptionsIndex.ts
  app/components/common/button/scan-button.tsx
  app/components/item-status/item-status-container.tsx
  app/item_status/page.tsx
  app/page.tsx
Labels: アイテムステータス

#143 Feature/90/118 アイテム詳細画面のテスト実装2
  app/components/common/Item/item-detail-card.tsx
  app/components/common/barcode/barcode-input-dialog.tsx
  app/page.tsx
  tests/item_detail/item_detail.spec.ts
Labels: アイテム詳細表示

#161 Release/90 アイテム詳細表示の実装
  app/api/item_detail/getItemsShow.ts
  app/components/common/Image/expandable-image.tsx
  app/components/common/Item/item-detail-card-container.tsx
  app/components/common/Item/item-detail-card.tsx
  app/components/common/barcode/barcode-input-dialog.tsx
  app/components/common/barcode/qr-code-reader.tsx
  app/components/item-detail/item-detail-container.tsx
  app/item_detail/[id]/page.tsx
  app/item_detail/page.tsx
  app/page.tsx
  next.config.js
  tests/item_detail/item_detail.spec.ts
Labels: アイテム詳細表示

#153 [動作確認]Release/123 棚卸し機能の実装
  app/api/item-location/useItemLocationsItemScan.ts
  app/api/stocktaking-location/getStocktakingLocationsShow.ts
  app/api/stocktaking-location/useStocktakingLocationCompleteScan.ts
  app/api/stocktaking-location/useStocktakingLocationItemScan.ts
  app/api/stocktaking-location/useStocktakingLocationMove.ts
  app/api/stocktaking/getStocktakingsCurrent.ts
  app/api/stocktaking/useStocktakingsComplete.ts
  app/api/stocktaking/useStocktakingsCreate.ts
  app/api/usePutRequest.ts
  app/components/common/barcode/barcode-button.tsx
  app/components/common/dialog/disable-back-dialog.tsx
  app/components/common/dialog/loading-dialog.tsx
  app/components/common/pages/header.tsx
  app/components/common/pages/sub-header.tsx
  app/components/stocktaking-location/location-item-tabs.tsx
  app/components/stocktaking-location/stocktaking-location-container.tsx
  app/components/stocktaking/stocktaking-container.tsx
  app/components/stocktaking/stocktaking-list.tsx
  app/components/stocktaking/stocktaking-row.tsx
  app/constants/location.ts
  app/loading.tsx
  app/page.tsx
  app/providers.tsx
  app/service/toCamelCaseObject.ts
  app/stocktaking/[id]/page.tsx
  app/stocktaking/page.tsx
  package.json
  yarn.lock
Labels: 棚卸し

#119 Feature/68 87 ピック済みのアイテムにはチェックが付くようにする
  app/api/coorde_pick/useCoordePicksPick.ts
  app/components/common/Item/item-card.tsx
  app/components/common/accordion/menu-accordion.tsx
  app/components/common/barcode/qr-code-reader-dialog.tsx
  app/components/common/barcode/qr-code-reader.tsx
  app/components/common/button/scan-button.tsx
  app/components/common/custom-hook/useDisableBrowserBack.ts
  app/components/common/dialog/disable-back-dialog.tsx
  app/components/common/dialog/error-dialog.tsx
  app/components/common/dialog/loading-dialog.tsx
  app/components/coorde-pick/coorde-pick-list.tsx
  app/coorde_pick/[chartId]/page.tsx
Labels: アイテムピック

#175 feat: InspectionGroupRowの作成
  app/components/inspection-group/inspection-group-list-item.tsx
Labels: 返却検品管理

#173 Feature/167/172 api関数作成
  app/api/inspection-groups/getInspectionGroupsIndex.ts
  app/api/inspection-groups/useInspectionGroupsCreate.ts
  app/api/inspection-groups/useInspectionGroupsEndRegistration.ts
  app/api/inspection-groups/useInspectionGroupsInspect.ts
  app/components/inspection-group/inspection-group-list-item.tsx
Labels: 返却検品管理

#180 Release/146 アイテムステータス一括更新機能の実装
  app/api/item_status/getOptionsIndex.ts
  app/api/item_status/useItemsBulkUpdateStatus.ts
  app/api/item_status/useItemsValidateBulkUpdateStatus.ts
  app/components/common/button/scan-button.tsx
  app/components/common/dialog/loading-dialog.tsx
  app/components/item-location/item-detail-fetcher.tsx
  app/components/item-location/item-location-container.tsx
  app/components/item-status/item-status-container.tsx
  app/components/stocktaking-location/stocktaking-location-container.tsx
  app/components/stocktaking/stocktaking-container.tsx
  app/item_status/page.tsx
  app/loading.tsx
Labels: アイテムステータス

#174 feat: Item Mediumカードの作成
  app/components/wasted_reason/wasted-reason-item-medium-card.tsx
Labels: 廃棄登録

#178 Feature/167/171 inspectiongroupcontainer page作成
  app/api/usePatchRequest.ts
  app/components/common/dialog/loading-dialog.tsx
  app/components/inspection-group/inspection-group-container.tsx
  app/components/inspection-group/inspection-group-dialogs.tsx
  app/components/inspection-group/inspection-group-list-item.tsx
  app/components/inspection-group/inspection-group-list.tsx
  app/components/item-location/item-detail-fetcher.tsx
  app/components/item-location/item-location-container.tsx
  app/components/stocktaking-location/stocktaking-location-container.tsx
  app/components/stocktaking/stocktaking-container.tsx
  app/inspection_group/page.tsx
  app/loading.tsx
  app/page.tsx
Labels: 返却検品管理

#189 [動作確認]Release/167 返却検品管理機能の実装
  app/api/inspection-groups/getInspectionGroupsIndex.ts
  app/api/inspection-groups/useInspectionGroupsCreate.ts
  app/api/inspection-groups/useInspectionGroupsEndRegistration.ts
  app/api/inspection-groups/useInspectionGroupsInspect.ts
  app/api/usePatchRequest.ts
  app/components/common/dialog/loading-dialog.tsx
  app/components/inspection-group/inspection-group-container.tsx
  app/components/inspection-group/inspection-group-dialogs.tsx
  app/components/inspection-group/inspection-group-list-item.tsx
  app/components/inspection-group/inspection-group-list.tsx
  app/inspection_group/page.tsx
  app/page.tsx
Labels: 返却検品管理
