Repository KiizanKiizan/Manene, pull requests merged in 2023-09, with the labels that each got.

#162 Feature/158/160 api関数作成
  app/api/wasted_reason/getWastedReasonIndex.ts
  app/api/wasted_reason/useWastedCreate.ts
  app/components/wasted_reason/wasted-reason-item-medium-card.tsx
Labels: 廃棄登録

#194 Bugfix/192 忘れ物headerとpathの追加
  app/api/useGetRequest.ts
  app/components/common/button/footer-button.tsx
  app/components/inspection-group/inspection-group-container.tsx
  app/components/lost_articles/lost-articles-confirm-fetcher.tsx
  app/components/lost_articles/lost-articles-container.tsx
  app/components/lost_articles/lost-articles-form.tsx
  app/components/stocktaking/stocktaking-container.tsx
  app/lost_articles/layout.tsx
  app/page.tsx
Labels: bug, 忘れ物管理

#200 feat: itemWastedSelectの作成
  app/components/wasted-reason/wasted-reason-item-medium-card.tsx
  app/components/wasted-reason/wasted-reason-select.tsx
Labels: 廃棄登録

#221 Feature/218 api関数作成
  app/api/cleaning-costs/fetchCleaningCostsItemDetail.ts
  app/api/cleaning-costs/getCreaningCostsChoice.ts
  app/api/cleaning-costs/useCleaningCostsCreate.ts
Labels: クリーニングコスト登録

#217 fix: 画像のアップロード処理が問題なく行われるよう修正
  app/components/inspecting-items/purchase-request-form.tsx
Labels: 返却検品中操作

#225 Feature/183/185 api関数の作成
  app/api/judge_throw_away/getJudgeThrowAwayOptions.ts
  app/api/judge_throw_away/useItemsJudgeThrowAway.ts
Labels: 廃棄判定

#226 Feature/183/186 judgethrowawayitemlistjudgethrowawayitemlistitem作成
  app/components/judge-throw-away/judge-throw-away-list-item.tsx
  app/components/judge-throw-away/judge-throw-away-list.tsx
Labels: 廃棄判定

#224 Feature/214/220 cleaningcostscontainer page作成
  app/api/cleaning-costs/getCreaningCostsChoice.ts
  app/cleaning_costs/layout.tsx
  app/cleaning_costs/page.tsx
  app/components/cleaning-costs/cleaning-costs-container.tsx
  app/page.tsx
Labels: クリーニングコスト登録

#204 Feature/158/203 wastedreasoncontainerpageの作成
  app/components/common/button/footer-button.tsx
  app/components/common/dialog/loading-dialog.tsx
  app/components/item-location/item-detail-fetcher.tsx
  app/components/item-location/item-location-container.tsx
  app/components/stocktaking-location/stocktaking-location-container.tsx
  app/components/stocktaking/stocktaking-container.tsx
  app/components/wasted-reason/wasted-reason-container.tsx
  app/components/wasted-reason/wasted-reason-qr-reader.tsx
  app/loading.tsx
  app/page.tsx
  app/wasted_reason/[id]/page.tsx
  app/wasted_reason/layout.tsx
  app/wasted_reason/page.tsx
Labels: 廃棄登録

#222 Feature/214/219 cleaningcostslistitemlist作成
  app/api/cleaning-costs/getCreaningCostsChoice.ts
  app/cleaning_costs/layout.tsx
  app/cleaning_costs/page.tsx
  app/components/cleaning-costs/cleaning-costs-container.tsx
  app/components/cleaning-costs/cleaning-costs-list-item.tsx
  app/components/cleaning-costs/cleaning-costs-list.tsx
  app/page.tsx
Labels: クリーニングコスト登録

#235 [動作確認]Release/158 廃棄登録機能の実装
  app/api/wasted_reason/getWastedReasonIndex.ts
  app/api/wasted_reason/useWastedCreate.ts
  app/components/item-location/item-detail-fetcher.tsx
  app/components/stocktaking-location/stocktaking-location-container.tsx
  app/components/wasted-reason/wasted-reason-container.tsx
  app/components/wasted-reason/wasted-reason-item-medium-card.tsx
  app/components/wasted-reason/wasted-reason-qr-reader.tsx
  app/components/wasted-reason/wasted-reason-select.tsx
  app/page.tsx
  app/providers.tsx
  app/wasted_reason/[id]/page.tsx
  app/wasted_reason/layout.tsx
  app/wasted_reason/page.tsx
Labels: 廃棄登録

#233 fix: overflowを適応させて特定の範囲でスクロールできるようにする
  app/components/stocktaking/stocktaking-container.tsx
Labels: bug, 棚卸し

#202 Feature/190/198 beforeinspectionscontainerpage作成
  app/before_inspection/page.tsx
  app/components/before-inspection/before-inspection-container.tsx
  app/components/common/Item/item-card.tsx
  app/components/common/barcode/qr-code-reader-dialog.tsx
  app/components/common/barcode/qr-code-reader.tsx
  app/components/common/button/footer-button.tsx
  app/components/common/button/scan-button.tsx
  app/components/common/pages/header.tsx
  app/components/inspection-group/inspection-group-container.tsx
  app/components/lost_articles/lost-articles-form.tsx
  app/components/stocktaking/stocktaking-container.tsx
  app/components/stocktaking/stocktaking-list.tsx
  app/page.tsx
Labels: 返却検品前登録

#229 [bugfix]アイテム詳細機能にヘッダーを追加する
  app/item_detail/layout.tsx
Labels: bug, アイテム詳細表示

#211 Feature/205/207 purchaserequestForm作成
  app/components/common/pages/section-header.tsx
  app/components/inspecting-items/purchase-request-form.tsx
Labels: 返却検品中操作

#242 Release/241 refactorメニュー画面をaccordionを使用しないようにする
  app/components/common/accordion/menu-accordion.tsx
  app/components/common/button/link-button-list-item.tsx
  app/components/common/button/link-button.tsx
  app/components/common/pages/sub-header.tsx
  app/page.tsx
Labels: refactor

#212 Feature/205/208 inspectingitemscontainerpage作成
  app/api/fetchData.ts
  app/components/common/Item/item-info-card.tsx
  app/components/common/card/chart-card.tsx
  app/components/common/dialog/disable-back-dialog.tsx
  app/components/inspecting-items/inspecting-items-container.tsx
  app/components/inspecting-items/inspecting-items-sender.tsx
  app/components/inspecting-items/purchase-request-form.tsx
  app/inspecting_items/page.tsx
  app/page.tsx
  app/providers.tsx
  app/utils/functions/getStatusText.ts
Labels: 返却検品中操作

#227 Feature/183/187 judgethrowawaycontainerpageの作成
  app/components/judge-throw-away/judge-throw-away-container.tsx
  app/components/judge-throw-away/judge-throw-away-sender.tsx
  app/judge_throw_away/layout.tsx
  app/judge_throw_away/page.tsx
  app/page.tsx
Labels: 廃棄判定

#252 [動作確認]Release/183 廃棄判定機能の実装
  .eslintrc.json
  app/api/cleaning-costs/fetchCleaningCostsItemDetail.ts
  app/api/cleaning-costs/getCreaningCostsChoice.ts
  app/api/cleaning-costs/useCleaningCostsCreate.ts
  app/api/judge_throw_away/getJudgeThrowAwayOptions.ts
  app/api/judge_throw_away/useItemsJudgeThrowAway.ts
  app/cleaning_costs/layout.tsx
  app/cleaning_costs/page.tsx
  app/components/cleaning-costs/cleaning-costs-container.tsx
  app/components/cleaning-costs/cleaning-costs-list-item.tsx
  app/components/cleaning-costs/cleaning-costs-list.tsx
  app/components/judge-throw-away/judge-throw-away-container.tsx
  app/components/judge-throw-away/judge-throw-away-list-item.tsx
  app/components/judge-throw-away/judge-throw-away-list.tsx
  app/components/judge-throw-away/judge-throw-away-sender.tsx
  app/judge_throw_away/layout.tsx
  app/judge_throw_away/page.tsx
  app/page.tsx
  middleware.ts
Labels: 廃棄登録
